"""
CEO Briefing Generator - Gold Tier Feature 8
Generates comprehensive Monday morning briefings with Odoo financial data
"""
import os
import sys
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional, Dict, Any, List
import json

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from src.database.db_manager import DatabaseManager


class CEOBriefing:
    """
    Generates comprehensive CEO briefings with:
    - Odoo financial data (invoices, expenses, balances)
    - Social media activity summaries
    - Proactive suggestions with approval files
    - Graceful degradation when Odoo unavailable
    """

    def __init__(self, vault_path: Optional[str] = None):
        """Initialize CEO briefing generator"""
        if vault_path is None:
            vault_path = os.environ.get('VAULT_PATH', str(Path.home() / 'Desktop' / 'PIAIC' / 'AI' / 'AI-EMPLOYEE-GOLD' / 'AI_Employee_Vault'))

        self.vault_path = Path(vault_path)
        self.monthly_budget = float(os.environ.get('MONTHLY_BUDGET', '5000'))

        # Ensure directories exist
        (self.vault_path / "Briefings").mkdir(parents=True, exist_ok=True)
        (self.vault_path / "Pending_Approval").mkdir(parents=True, exist_ok=True)

        # Initialize database
        db_path = self.vault_path / "Database" / "ai_employee.db"
        if db_path.exists():
            self.db = DatabaseManager(str(db_path))
        else:
            self.db = None

    def generate(self, odoo_data: Optional[Dict[str, Any]] = None) -> str:
        """
        Generate CEO briefing.
        Returns filename of generated briefing.
        """
        today = datetime.now()
        day_name = today.strftime("%A")
        filename = f"{today.strftime('%Y-%m-%d')}_{day_name}_Briefing.md"
        briefing_path = self.vault_path / "Briefings" / filename

        # Gather data
        revenue_section = self._generate_revenue_section(odoo_data)
        expense_section = self._generate_expense_section(odoo_data)
        cash_section = self._generate_cash_section(odoo_data)
        tasks_section = self._generate_tasks_section()
        social_section = self._generate_social_section()
        suggestions_section = self._generate_suggestions_section(odoo_data)

        # Build briefing
        content = f"""# Monday Morning CEO Briefing — {today.strftime('%B %d, %Y')}

## Executive Summary

{self._generate_executive_summary(odoo_data)}

{revenue_section}

{expense_section}

{cash_section}

{tasks_section}

{social_section}

## Bottlenecks

{self._generate_bottlenecks_section()}

{suggestions_section}

## Upcoming Deadlines

{self._generate_deadlines_section()}

---

Generated by AI Employee Gold Tier
Data sources: {"Odoo, SQLite, Social Media Logs" if odoo_data else "SQLite, Social Media Logs (⚠️ Odoo unavailable)"}
"""

        briefing_path.write_text(content, encoding='utf-8')
        return filename

    def _generate_executive_summary(self, odoo_data: Optional[Dict[str, Any]]) -> str:
        """Generate executive summary bullets"""
        summary = []

        if odoo_data:
            total_invoiced = sum(inv.get('amount_total', 0) for inv in odoo_data.get('invoices', []))
            total_expenses = sum(exp.get('total_amount', 0) for exp in odoo_data.get('expenses', []))
            overdue_count = len(odoo_data.get('overdue_invoices', []))

            summary.append(f"- Revenue this week: ${total_invoiced:,.2f}")
            summary.append(f"- Expenses this week: ${total_expenses:,.2f}")
            if overdue_count > 0:
                summary.append(f"- {overdue_count} overdue invoice(s) requiring attention")
        else:
            summary.append("- ⚠️ Odoo unavailable - financial data may be stale")

        # Social media summary
        social_count = self._count_social_posts()
        if social_count > 0:
            summary.append(f"- {social_count} social media posts this week")

        return "\n".join(summary)

    def _generate_revenue_section(self, odoo_data: Optional[Dict[str, Any]]) -> str:
        """Generate revenue section"""
        if not odoo_data:
            return """## Revenue (from Odoo)

⚠️ **Odoo unavailable - data may be stale**"""

        invoices = odoo_data.get('invoices', [])
        overdue = odoo_data.get('overdue_invoices', [])

        total_invoiced = sum(inv.get('amount_total', 0) for inv in invoices)
        total_overdue = sum(inv.get('amount_residual', 0) for inv in overdue)

        content = f"""## Revenue (from Odoo)

**Total Invoiced This Week**: ${total_invoiced:,.2f}
**Overdue Invoices**: ${total_overdue:,.2f} ({len(overdue)} invoices)

Top 3 invoices:
"""

        # Sort by amount and take top 3
        sorted_invoices = sorted(invoices, key=lambda x: x.get('amount_total', 0), reverse=True)[:3]
        for inv in sorted_invoices:
            partner_name = inv.get('partner_id', [None, 'Unknown'])[1]
            amount = inv.get('amount_total', 0)
            state = inv.get('state', 'unknown')
            content += f"- {partner_name} - ${amount:,.2f} - {state}\n"

        return content

    def _generate_expense_section(self, odoo_data: Optional[Dict[str, Any]]) -> str:
        """Generate expense section"""
        if not odoo_data:
            return """## Expenses (from Odoo)

⚠️ **Odoo unavailable - data may be stale**"""

        expenses = odoo_data.get('expenses', [])
        total_expenses = sum(exp.get('total_amount', 0) for exp in expenses)
        budget_remaining = self.monthly_budget - total_expenses

        content = f"""## Expenses (from Odoo)

**Total Expenses This Week**: ${total_expenses:,.2f}
**Budget Remaining**: ${budget_remaining:,.2f} / ${self.monthly_budget:,.2f} monthly

Top 3 expense categories:
"""

        # Group by category and sort
        category_totals = {}
        for exp in expenses:
            category = exp.get('product_id', [None, 'Uncategorized'])[1]
            amount = exp.get('total_amount', 0)
            category_totals[category] = category_totals.get(category, 0) + amount

        sorted_categories = sorted(category_totals.items(), key=lambda x: x[1], reverse=True)[:3]
        for category, amount in sorted_categories:
            content += f"- {category} - ${amount:,.2f}\n"

        return content

    def _generate_cash_section(self, odoo_data: Optional[Dict[str, Any]]) -> str:
        """Generate cash position section"""
        if not odoo_data:
            return """## Cash Position (from Odoo)

⚠️ **Odoo unavailable - data may be stale**"""

        balance_data = odoo_data.get('account_balance', {})
        balance = balance_data.get('balance', 0)
        currency = balance_data.get('currency', 'USD')

        return f"""## Cash Position (from Odoo)

**Current Balance**: ${balance:,.2f} {currency}
**Change from Last Week**: (tracking not yet implemented)"""

    def _generate_tasks_section(self) -> str:
        """Generate task completion section"""
        # This would query SQLite for task stats
        # For now, return placeholder
        return """## Task Completion This Week

**Total Tasks Completed**: (querying database...)
- Email: (querying...)
- WhatsApp: (querying...)
- LinkedIn: (querying...)
- Filesystem: (querying...)

**Average Response Time**: (calculating...)
**Failed Tasks**: (checking...)"""

    def _generate_social_section(self) -> str:
        """Generate social media activity section"""
        social_counts = self._count_social_posts_by_platform()

        total = sum(social_counts.values())

        content = f"""## Social Media Activity

**Total Posts This Week**: {total}
- LinkedIn: {social_counts.get('linkedin', 0)} posts
- Facebook: {social_counts.get('facebook', 0)} posts
- Instagram: {social_counts.get('instagram', 0)} posts
- Twitter: {social_counts.get('twitter', 0)} tweets

**Engagement Summary**: (manual tracking required)"""

        return content

    def _generate_bottlenecks_section(self) -> str:
        """Generate bottlenecks section"""
        return "(Checking for stuck tasks and recurring errors...)"

    def _generate_suggestions_section(self, odoo_data: Optional[Dict[str, Any]]) -> str:
        """Generate proactive suggestions and create approval files"""
        suggestions = []

        if odoo_data:
            # Check for overdue invoices
            overdue = odoo_data.get('overdue_invoices', [])
            for inv in overdue:
                partner_name = inv.get('partner_id', [None, 'Unknown'])[1]
                amount = inv.get('amount_residual', 0)
                due_date = inv.get('invoice_date_due', '')

                # Calculate days overdue
                try:
                    due = datetime.fromisoformat(due_date)
                    days_overdue = (datetime.now() - due).days
                except:
                    days_overdue = 0

                if days_overdue > 7:
                    # Create approval file
                    approval_file = self._create_followup_approval(partner_name, amount, days_overdue)
                    suggestions.append(f"1. **Follow up on overdue invoice from {partner_name}**\n   - Amount: ${amount:,.2f}\n   - Days overdue: {days_overdue}\n   - Approval file: `/Pending_Approval/{approval_file}`")

        if not suggestions:
            suggestions.append("No proactive suggestions at this time.")

        content = "## Proactive Suggestions\n\n"
        content += "\n\n".join(suggestions)

        return content

    def _generate_deadlines_section(self) -> str:
        """Generate upcoming deadlines section"""
        return "(Calendar integration not yet implemented)"

    def _count_social_posts(self) -> int:
        """Count total social media posts this week"""
        counts = self._count_social_posts_by_platform()
        return sum(counts.values())

    def _count_social_posts_by_platform(self) -> Dict[str, int]:
        """Count social media posts by platform from logs"""
        counts = {'linkedin': 0, 'facebook': 0, 'instagram': 0, 'twitter': 0}

        logs_dir = self.vault_path / "Logs"
        if not logs_dir.exists():
            return counts

        # Check last 7 days of logs
        for i in range(7):
            date = datetime.now() - timedelta(days=i)
            log_file = logs_dir / f"{date.strftime('%Y-%m-%d')}.json"

            if log_file.exists():
                try:
                    with open(log_file, 'r') as f:
                        for line in f:
                            try:
                                log = json.loads(line.strip())
                                action_type = log.get('action_type', '')

                                if 'linkedin' in action_type and log.get('result') == 'success':
                                    counts['linkedin'] += 1
                                elif 'facebook' in action_type and log.get('result') == 'success':
                                    counts['facebook'] += 1
                                elif 'instagram' in action_type and log.get('result') == 'success':
                                    counts['instagram'] += 1
                                elif 'twitter' in action_type and log.get('result') == 'success':
                                    counts['twitter'] += 1
                            except json.JSONDecodeError:
                                continue
                except Exception:
                    continue

        return counts

    def _create_followup_approval(self, client_name: str, amount: float, days_overdue: int) -> str:
        """Create approval file for invoice follow-up"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"EMAIL_followup_{timestamp}.md"
        approval_path = self.vault_path / "Pending_Approval" / filename

        content = f"""---
type: email
approval_id: EMAIL_followup_{timestamp}
---

## Email Follow-up Request

**To**: {client_name}
**Subject**: Payment Reminder - Invoice Overdue

### Message

Dear {client_name},

I hope this message finds you well. I wanted to follow up regarding the outstanding invoice of ${amount:,.2f}, which is now {days_overdue} days overdue.

Could you please provide an update on the payment status? If there are any issues or concerns, I'd be happy to discuss them.

Thank you for your attention to this matter.

Best regards

---

## Approval Required

This email will be sent to {client_name}.
Approve to proceed, reject to cancel.
"""

        approval_path.write_text(content, encoding='utf-8')
        return filename


def main():
    """Main entry point for testing"""
    import argparse

    parser = argparse.ArgumentParser(description='CEO Briefing Generator')
    parser.add_argument('--test', action='store_true', help='Generate test briefing')

    args = parser.parse_args()

    briefing = CEOBriefing()

    if args.test:
        # Generate with mock data
        mock_data = {
            "invoices": [
                {"id": 1, "name": "INV/001", "partner_id": [1, "Test Client"], "amount_total": 5000.0, "state": "posted"}
            ],
            "overdue_invoices": [],
            "expenses": [
                {"id": 1, "name": "Test Expense", "total_amount": 100.0, "product_id": [1, "Office"]}
            ],
            "account_balance": {"balance": 25000.0, "currency": "USD"}
        }

        filename = briefing.generate(odoo_data=mock_data)
        print(f"✓ Test briefing generated: {filename}")
    else:
        print("Use --test to generate a test briefing")


if __name__ == '__main__':
    main()
