"""
Error Recovery and Graceful Degradation - Gold Tier Feature 9
Provides retry logic and system alert generation for external API failures
"""
import os
import time
import functools
from pathlib import Path
from datetime import datetime
from typing import Optional, Callable, Any


def with_retry(max_attempts: int = 3, base_delay: float = 1.0, max_delay: float = 4.0):
    """
    Decorator that retries a function with exponential backoff.

    Args:
        max_attempts: Maximum number of retry attempts
        base_delay: Initial delay between retries in seconds
        max_delay: Maximum delay between retries in seconds

    Usage:
        @with_retry(max_attempts=3, base_delay=1, max_delay=4)
        def call_external_api():
            ...
    """
    def decorator(func: Callable) -> Callable:
        @functools.wraps(func)
        def wrapper(*args, **kwargs) -> Any:
            last_exception = None

            for attempt in range(1, max_attempts + 1):
                try:
                    return func(*args, **kwargs)
                except Exception as e:
                    last_exception = e

                    if attempt == max_attempts:
                        # Last attempt failed, raise the exception
                        raise

                    # Calculate exponential backoff delay
                    delay = min(base_delay * (2 ** (attempt - 1)), max_delay)

                    print(f"Attempt {attempt}/{max_attempts} failed: {e}. Retrying in {delay}s...")
                    time.sleep(delay)

            # Should never reach here, but just in case
            if last_exception:
                raise last_exception

        return wrapper
    return decorator


def create_system_alert(
    vault_path: str,
    service: str,
    error: str,
    action_required: bool = True
) -> str:
    """
    Create a SYSTEM_ALERT file for service failures.

    Args:
        vault_path: Path to AI_Employee_Vault
        service: Service name (gmail, odoo, facebook, etc.)
        error: Error message
        action_required: Whether human action is required

    Returns:
        Filename of created alert
    """
    vault = Path(vault_path)
    needs_action = vault / "Needs_Action"
    needs_action.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    service_upper = service.upper()
    filename = f"SYSTEM_ALERT_{service_upper}_{timestamp}.md"
    alert_path = needs_action / filename

    content = f"""---
type: system_alert
service: {service}
error: {error}
timestamp: {datetime.now().isoformat()}
action_required: {str(action_required).lower()}
---

## System Alert

**Service**: {service.title()}
**Status**: Unavailable
**Error**: {error}

## Impact

The {service} service is currently unavailable. Other services continue running normally.

## What to Do

{"Check " + service + " credentials and connectivity." if action_required else "This is informational only. The system will retry automatically."}

## Technical Details

- Timestamp: {datetime.now().isoformat()}
- Service: {service}
- Error: {error}

---

Generated by AI Employee Error Recovery System
"""

    alert_path.write_text(content, encoding='utf-8')
    return filename


def handle_service_failure(
    service: str,
    error: Exception,
    vault_path: Optional[str] = None,
    action_required: bool = True
) -> None:
    """
    Handle service failure by creating system alert.

    Args:
        service: Service name
        error: Exception that occurred
        vault_path: Path to vault (defaults to env var)
        action_required: Whether human action is required
    """
    if vault_path is None:
        vault_path = os.environ.get(
            'VAULT_PATH',
            str(Path.home() / 'Desktop' / 'PIAIC' / 'AI' / 'AI-EMPLOYEE-GOLD' / 'AI_Employee_Vault')
        )

    error_message = str(error)
    create_system_alert(vault_path, service, error_message, action_required)

    print(f"⚠️ {service.title()} service failure: {error_message}")
    print(f"System alert created. Other services continue running.")


# Example usage patterns for different services
def example_gmail_with_retry():
    """Example: Gmail API call with retry"""
    @with_retry(max_attempts=3, base_delay=1, max_delay=4)
    def check_gmail():
        # Gmail API call here
        pass

    try:
        check_gmail()
    except Exception as e:
        handle_service_failure('gmail', e)


def example_odoo_with_retry():
    """Example: Odoo API call with retry"""
    @with_retry(max_attempts=3, base_delay=1, max_delay=4)
    def query_odoo():
        # Odoo JSON-RPC call here
        pass

    try:
        query_odoo()
    except Exception as e:
        handle_service_failure('odoo', e)


def example_social_media_with_retry():
    """Example: Social media post with retry"""
    @with_retry(max_attempts=3, base_delay=1, max_delay=4)
    def post_to_facebook():
        # Playwright automation here
        pass

    try:
        post_to_facebook()
    except Exception as e:
        handle_service_failure('facebook', e)
